version: 2.1

orbs:
    helm: banzaicloud/helm@0.0.8
    docker: circleci/docker@0.5.13
workflows:
    version: 2
    helm-chart:
        jobs:
            -   helm/publish-chart:
                    context: helm
                    charts-dir: chart
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /chart\/log-generator\/\d+.\d+.\d+/