version: 2.1

orbs:
    helm: banzaicloud/helm@0.0.3
    docker: circleci/docker@0.5.13
workflows:
    version: 2
    helm-chart:
        jobs:
            -   helm/lint-chart:
                    chart-path: chart/log-generator
                    filters:
                        tags:
                            ignore: /.*/

            -   helm/publish-chart:
                    context: helm
                    chart-path: chart/log-generator
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /chart\/log-generator\/\d+.\d+.\d+/