name: Build and test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build
      run: make GOFLAGS="-v" build

    - name: Test
      run: make GOFLAGS="-v" test

  artifacts:
    name: Artifacts
    uses: kube-logging/logging-operator/.github/workflows/artifacts.yaml@4.3.0
    with:
      publish: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
